development:
  adapter: postgresql
  encoding: unicode
  database: db/sample_app_development
  pool: 5
  username: nantas
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: db/sample_app_test
  pool: 5
  username: nantas
  password: password1

production:
  adapter: sqlite3
  database: db/sample_app_production
  pool: 5
  timeout: 5000
